### PR TITLE
#177 Switch VSCode integration from View to Editor

### LINKED ISSUE #177: Switch VSCode integration from View to Editor
.wf files are opened with a text editor, can we make the GLSP view default?

### PR DESCRIPTION
**Pull request by tortmayr**
- Rework glsp vscode extension glue code to use Custom Editor API instead of plain web view.
- Implement generic reusable GLSPDiagramEditor Provider
- Provide glue code to automatically start and embedded GLSP Java Server instead of having to launch the server externally
- Update readme and documentation
- Update/Adapt example extension
- Update & cleanup metadata and package names
- Enable proper debugging of typescript sources
- Update example gif

Fixes eclipse-glsp/glsp/issues/177

### CODE REVIEW

**Review by planger — APPROVED** [review]
Excellent work! Thanks a lot!

I tested the following which worked fine:
  * Opening the diagram with downloaded GLSP workflow server
  * Changing the diagram --> dirty state correct
  * Undoing changes --> dirty state correct
  * Saving and reopening --> correct file state
  * Command palette within diagram editor
  * Fit to screen action from global quick commands

When executing the `Center selection` command, I got an error though:
```
Command 'Workflow Diagram: Center selection' resulted in an error (command 'workflow.diagram.diagram.center' not found)
```

**Comment by JonasHelming** [comment]
Question: Would it be a lot of effort to enable a "auto layout" command? @tortmayr

**Comment by tortmayr** [comment]
@planger Thanks for the review, the Center selection command should be fixed now.
FYI it is also possible to execute these commands via Keyboard shortcuts (`alt + c`, `alt+ f`)

@JonasHelming  Sure no problem. I added the same "auto layout" command that we use in the Theia integration. It can be triggered via vscode command palette (`F1`) or by using the `alt + l` keyboard shortcut

**Review by planger — APPROVED** [review]
Awesome, thanks!

**Comment by JonasHelming** [comment]
Great work!

**Review by JonasHelming — APPROVED** [review]

**Pull request merged**
